baseURL: https://realorangeone.github.io/hugo-theme-revealjs
title: Hugo Theme RevealJS
themesDir: "../../"
theme: "hugo-theme-revealjs"

params:
    revealjs:
        controls: true
        progress: true
        history: true
        center: true

disableKinds:
    - taxonomy
    - taxonomyTerm
